name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@main
        env:
          HUGO_VERSION: 0.143.0
          HUGO_EXTENDED: true
          TARGET_REPO: rex-rs/rex-rs.github.io
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
